## Bài 1. Tạo Tensor cơ bản
Tạo Tensor số nguyên kích thước `2 × 3` và kiểm tra kích thước, số chiều, kiểu dữ liệu.

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print("Tensor a:")
print(a)
print("Kích thước:", a.shape)
print ("Chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)


Tensor a:
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Chiều: 2
Kiểu dữ liệu: torch.int32


## Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
f = torch.full((5,5 ), 10)

print("Tensor rand:\n", a)
print("\nTensor randn:\n", b)
print("\nTensor zeros:\n", c)
print("\nTensor ones:\n", d)
print("\nTensor eye:\n", e)
print("\nTensor 5x5 chứa toàn giá trị 10:\n", f)

Tensor rand:
 tensor([[0.6445, 0.8168, 0.5783, 0.8987],
        [0.6479, 0.4710, 0.9540, 0.8944],
        [0.4788, 0.7087, 0.7549, 0.5207]])

Tensor randn:
 tensor([[-0.0311,  2.1560, -0.1166,  0.1585],
        [ 0.5253, -0.9427, -0.3641, -1.0259],
        [-0.4953,  0.2491, -0.8003,  1.2966]])

Tensor zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor eye:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5x5 chứa toàn giá trị 10:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [3]:
import torch
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Bài 4. Slicing và Indexing

Truy xuất dữ liệu từ Tensor nhiều chiều và lấy hai phần tử cuối cùng trên chiều thứ ba.

In [4]:
import torch

a = torch.randn(3, 4, 5)

print("Shape của a:", a.shape)
print("Shape của a[1]:", a[1].shape)
print("Shape của a[1:, 2:4]:", a[1:, 2:4].shape)

last_two = a[:, :, -2:]
print("Shape của hai phần tử cuối:", last_two.shape)
print(last_two)

Shape của a: torch.Size([3, 4, 5])
Shape của a[1]: torch.Size([4, 5])
Shape của a[1:, 2:4]: torch.Size([2, 2, 5])
Shape của hai phần tử cuối: torch.Size([3, 4, 2])
tensor([[[ 0.6766,  0.3152],
         [ 0.2696, -0.9646],
         [-0.1716, -1.3326],
         [-0.0325,  2.4617]],

        [[-0.3822,  2.4178],
         [ 0.3405,  0.1416],
         [-0.4602, -0.2391],
         [ 0.2141, -0.3349]],

        [[ 0.3995, -0.0993],
         [-0.7666, -1.1960],
         [-0.0175,  0.0727],
         [ 1.0351, -0.3923]]])


## Bài 5. Reshape và Flatten

Thay đổi hình dạng Tensor nhưng không thay đổi số phần tử.

In [5]:
import torch

a = torch.randn(3, 4)

print("Shape ban đầu:", a.shape)
print("Số phần tử ban đầu:", a.numel())

b = a.ravel()
print("\nFlatten:")
print(b)
print("Shape:", b.shape)

c = a.reshape(3, 2, 2)
print("\nReshape 3 x 2 x 2:")
print(c)

d = a.reshape(2, 6)
print("\nReshape 2 x 6:")
print(d)
print("Shape:", d.shape)
print("Số phần tử sau reshape:", d.numel())

Shape ban đầu: torch.Size([3, 4])
Số phần tử ban đầu: 12

Flatten:
tensor([-1.1502,  1.3050,  0.2850,  0.2425, -0.1161,  2.2568, -0.7772,  0.6759,
         2.1047,  0.5337, -0.4504, -0.8640])
Shape: torch.Size([12])

Reshape 3 x 2 x 2:
tensor([[[-1.1502,  1.3050],
         [ 0.2850,  0.2425]],

        [[-0.1161,  2.2568],
         [-0.7772,  0.6759]],

        [[ 2.1047,  0.5337],
         [-0.4504, -0.8640]]])

Reshape 2 x 6:
tensor([[-1.1502,  1.3050,  0.2850,  0.2425, -0.1161,  2.2568],
        [-0.7772,  0.6759,  2.1047,  0.5337, -0.4504, -0.8640]])
Shape: torch.Size([2, 6])
Số phần tử sau reshape: 12


## Bài 6. Phép toán và nhân ma trận

Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [6]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a * b:")
print(a * b)

print("\na @ b.T:")
print(a @ b.T)

print("Shape của a * b:", (a * b).shape)
print("Shape của a @ b.T:", (a @ b.T).shape)


a * b:
tensor([[-0.6424, -0.1896,  0.0213],
        [ 0.2492,  1.1515, -0.0238]])

a @ b.T:
tensor([[-0.8107,  0.6441],
        [-2.3573,  1.3769]])
Shape của a * b: torch.Size([2, 3])
Shape của a @ b.T: torch.Size([2, 2])


## Bài 7. Các hàm thống kê trên Tensor

Tính trung bình, độ lệch chuẩn và tổng tích lũy theo các chiều khác nhau.

In [7]:
import torch

a = torch.randn(3, 4)

print("Tensor a:")
print(a)

print("\nMean theo cột:")
print(torch.mean(a, dim=0))

print("\nĐộ lệch chuẩn theo cột:")
print(torch.std(a, dim=0))

print("\nTổng tích lũy theo cột:")
print(torch.cumsum(a, dim=0))

print("\nMean theo hàng:")
print(torch.mean(a, dim=1))

print("\nĐộ lệch chuẩn theo hàng:")
print(torch.std(a, dim=1))

print("\nTổng tích lũy theo hàng:")
print(torch.cumsum(a, dim=1))


Tensor a:
tensor([[-0.0026,  1.2152,  0.7042, -0.3836],
        [-0.5414, -1.2370, -0.7700, -1.5130],
        [-0.0859,  0.7278,  1.0374, -1.0196]])

Mean theo cột:
tensor([-0.2099,  0.2354,  0.3239, -0.9721])

Độ lệch chuẩn theo cột:
tensor([0.2900, 1.2982, 0.9618, 0.5662])

Tổng tích lũy theo cột:
tensor([[-2.5950e-03,  1.2152e+00,  7.0417e-01, -3.8360e-01],
        [-5.4397e-01, -2.1786e-02, -6.5805e-02, -1.8967e+00],
        [-6.2985e-01,  7.0606e-01,  9.7162e-01, -2.9163e+00]])

Mean theo hàng:
tensor([ 0.3833, -1.0154,  0.1649])

Độ lệch chuẩn theo hàng:
tensor([0.7146, 0.4403, 0.9209])

Tổng tích lũy theo hàng:
tensor([[-2.5950e-03,  1.2126e+00,  1.9168e+00,  1.5332e+00],
        [-5.4138e-01, -1.7784e+00, -2.5484e+00, -4.0614e+00],
        [-8.5875e-02,  6.4197e-01,  1.6794e+00,  6.5979e-01]])


## Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

### Câu a: Với `y = x²` tại `x = 3.6`

Ta có `dy/dx = 2x = 7.2` tại `x = 3.6`.

In [8]:
import torch

x = torch.tensor(3.6, requires_grad=True)

y = x * x
y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)


x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### Câu b: Với `y = 3x² + 2x + 1`

Đạo hàm là `dy/dx = 6x + 2`. Tại `x = 3.6`, gradient bằng `23.6`.

In [9]:
import torch

x = torch.tensor(3.6, requires_grad=True)

y = 3 * x**2 + 2 * x + 1
y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)


x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức `y = x² + 2x + 3`, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [10]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([1, 2, 3])

N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("\nLearned coefficients:")
print(w)
print("\nMSE cuối cùng:", mse.item())


Initial coefficients:
tensor([[0.3367],
        [0.1288],
        [0.2345]], requires_grad=True)

Learned coefficients:
tensor([[1.0087],
        [2.0033],
        [2.5330]], requires_grad=True)

MSE cuối cùng: 0.13043160736560822


## Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [11]:
import random
import torch

torch.manual_seed(42)

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1**2 + y2**2 + y3**2 + y4**2

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

print("\nKiểm tra nghiệm:")
print("A + B =", (A + B).item())
print("C - D =", (C - D).item())
print("A + C =", (A + C).item())
print("B - D =", (B - D).item())


A = 4.36245059967041
B = 4.637495040893555
C = 3.6375300884246826
D = 2.6375105381011963

Kiểm tra nghiệm:
A + B = 8.999945640563965
C - D = 1.0000195503234863
A + C = 7.999980926513672
B - D = 1.9999845027923584


## 3. Bài tập áp dụng
### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

#### Yêu cầu 1: Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

In [12]:
import torch

X = torch.arange(1, 25)

print("Tensor X ban đầu:")
print(X)

print("\nReshape thành 4 x 6:")
print(X.reshape(4, 6))

print("\nReshape thành 2 x 12:")
print(X.reshape(2, 12))

print("\nReshape thành 2 x 3 x 4:")
print(X.reshape(2, 3, 4))


Tensor X ban đầu:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

Reshape thành 4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

Reshape thành 2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

Reshape thành 2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


#### Yêu cầu 2: Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [13]:
import torch

A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình của A theo cột:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn của A theo cột:")
print(torch.std(A, dim=0))


A + B:
tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])

A * B:
tensor([[ 0.3738, -0.2177, -0.2319,  0.2207],
        [-1.4846, -0.1523, -1.6911,  0.4789],
        [ 0.6244,  0.1835, -0.1753,  0.6434]])

A / B:
tensor([[ 0.3032, -0.0762, -0.2371,  0.2404],
        [-0.8493, -0.2280, -2.8834,  0.8500],
        [ 0.3413,  0.3895, -1.6320,  1.0181]])

Trung bình của A theo cột:
tensor([-0.1082,  0.0699,  0.9925,  0.1339])

Độ lệch chuẩn của A theo cột:
tensor([0.8810, 0.2325, 1.0635, 0.7285])


#### Yêu cầu 3: Cho `y = 2x² + 5x + 3`. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [14]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = 2 * x**2 + 5 * x + 3
y.backward()

print("y =", y.item())
print("dy/dx =", x.grad.item())


y = 21.0
dy/dx = 13.0


#### Yêu cầu 4: Thay đa thức trong Bài 9 bằng `y = 2x² - 3x + 5`; huấn luyện và cho biết các hệ số tìm được.

In [15]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([2, -3, 5])

N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

w = torch.randn(3, 1, requires_grad=True)
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean((y - y_pred)**2)
    mse.backward()
    optimizer.step()

print("\nLearned coefficients:")
print(w)
print("\nMSE cuối cùng:", mse.item())


Initial coefficients:
tensor([[0.3367],
        [0.1288],
        [0.2345]], requires_grad=True)

Learned coefficients:
tensor([[ 2.0181],
        [-2.9922],
        [ 4.0276]], requires_grad=True)

MSE cuối cùng: 0.564120888710022
